version: "3"
services:
  bottender:
    container_name: dpo-bottender
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "1990:2700"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    network_mode: "bridge"
  browser:
    container_name: dpo-browser
    build: 
        context: .
        dockerfile: ./src/Dockerfile
    restart: unless-stopped
    ports:
      - "1991:3000"
    volumes:
      - .:/home/node/app_browser
      - /home/node/app_browser/node_modules
    network_mode: "bridge"
  dialogflow:
    container_name: dpo-dialogflow
    build: 
        context: .
        dockerfile: ./dialogflow/Dockerfile
    restart: unless-stopped
    ports:
      - "1992:2777"
    volumes:
      - .:/home/node/app_df
      - /home/node/app_df/node_modules
    network_mode: "bridge"
  redis:
    container_name: dpo-redis
    image: 'redis:4-alpine'
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'

