version: "3"
services:
  app:
    container_name: bottender-chatbot
    build: .
    restart: unless-stopped
    ports:
      - "2004:3000"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    network_mode: "bridge"

