version: "3"
networks:
  dpo:
services:
  bottender:
    container_name: 'dpo-bottender-${PROJECT_NAME}'
    build:
      context: .
      dockerfile: ./src/Dockerfile
    restart: unless-stopped
    ports:
      - "1992:5000"
    expose:
      - "1992"
    # volumes:
    #   - .:/home/node/app
    #   - /home/node/app/node_modules
  browser:
    container_name: 'dpo-browser-${PROJECT_NAME}'
    build: 
        context: .
        dockerfile: ./Dockerfile
        args:
          EXPOSED_PORT: '${PORT}'
    restart: unless-stopped
    ports:
      - "${REACT_APP_BROWSER_PORT}:5000"
    networks:
      - dpo
  proxy:
    container_name: 'dpo-proxy-${PROJECT_NAME}'
    restart: unless-stopped
    build: 
        context: ./proxy
        dockerfile: ./Dockerfile
    ports:
      - "${REACT_APP_PROXY_PORT}:${REACT_APP_PROXY_PORT}"
    expose:
      - "${REACT_APP_PROXY_PORT}"
    networks:
      - dpo
    volumes:
      - ./proxy:/home/node/dpo_proxy_app/proxy
      - /home/node/dpo_proxy_app/proxy/node_modules
  redis:
    image: "redis"
    container_name: 'dpo-redis-${PROJECT_NAME}'
    command: "redis-server /usr/local/etc/redis/redis.conf --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD}"
    volumes:
    - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
     - "${REDIS_PORT}:${REDIS_PORT}"
    restart: unless-stopped
    networks:
      - dpo
