version: "3"
services:
  # bottender:
  #   container_name: dpo-bottender
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - "1990:5000"
  #   volumes:
  #     - .:/home/node/app
  #     - /home/node/app/node_modules
  #   network_mode: "bridge"
  # dialogflow:
  #   container_name: dpo-dialogflow
  #   build: 
  #       context: .
  #       dockerfile: ./dialogflow/Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - "1992:2777"
  #   volumes:
  #     - .:/home/node/app_df
  #     - /home/node/app_df/node_modules
  #   network_mode: "bridge"
  browser:
    container_name: dpo-browser
    build: 
        context: .
        dockerfile: ./src/Dockerfile
    restart: unless-stopped
    ports:
      - "1992:3000"
    volumes:
      - .:/home/node/app_browser
      - /home/node/app_browser/node_modules
    network_mode: "bridge"

