version: "3"
networks:
  dpo:
services:
  bottender:
    container_name: dpo-bottender
    build:
      context: .
      dockerfile: ./src/Dockerfile
    restart: unless-stopped
    ports:
      - "1992:5000"
    expose:
      - "1992"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    # network_mode: "bridge"
  browser:
    container_name: dpo-browser
    build: 
        context: .
        dockerfile: ./src/Dockerfile
    restart: unless-stopped
    ports:
      - "${REACT_APP_BROWSER_PORT}:${REACT_APP_BROWSER_PORT}"
    volumes:
      - .:/home/node/app_browser
    networks:
      - dpo
  proxy:
    container_name: dpo-proxy
    restart: unless-stopped
    build: 
        context: ./proxy
        dockerfile: ./Dockerfile
    ports:
      - "${REACT_APP_PROXY_PORT}:${REACT_APP_PROXY_PORT}"
    expose:
      - "${REACT_APP_PROXY_PORT}"
    links:
      - redis
    networks:
      - dpo
